### ISSUE TITLE
Crud not worked

### ISSUE THREAD

**Issue by RedDevilHat** [appzcoder/crud-generator#169]
Hi i try

`php artisan crud:generate Test --fields_from_file="resources/assets/form-generator/test.json" --view-path=test --controller-namespace=Test --route-group=test`

and i have

> Call to undefined method Appzcoder\CrudGenerator\Commands\CrudControllerCommand::qualifyClass()

Laravel 5.1.*
PHP 7.1

`
$ php artisan vendor:publish --provider="Appzcoder\CrudGenerator\CrudGeneratorServiceProvider"
Copied File [/vendor/appzcoder/crud-generator/config/crudgenerator.php] To [/config/crudgenerator.php]
Copied Directory [/vendor/appzcoder/crud-generator/publish/views] To [/resources/views]
Copied File [/vendor/appzcoder/crud-generator/publish/css/app.css] To [/public/css/app.css]
Copied Directory [/vendor/appzcoder/crud-generator/src/stubs] To [/resources/crud-generator]
Publishing complete for tag []!
`

**Comment by glgeorgiev** [comment]
Yes, the current version - 2.0.2 has a bug.
The bugfix is now merged, but a new version should be released ASAP!

**Comment by sohelamin** [comment]
Fixed now

**Comment by khe817** [comment]
Hi there,

I still get the same error for latest version 2.0.3 running the same command as the original poster.

Laravel 5.3
PHP 5.6
